export const DEFAULT_DEEPSEEK_PROVIDER_MODEL = 'deepseek-v4-flash';
export const DEFAULT_DEEPSEEK_PROVIDER_API_KEY_ENV = 'DEEPSEEK_API_KEY';
export const DEFAULT_DEEPSEEK_PROVIDER_API_KEY_REFERENCE = `$ENV:${DEFAULT_DEEPSEEK_PROVIDER_API_KEY_ENV}`;
export const DEFAULT_DEEPSEEK_PROVIDER_BASE_URL = 'https://api.deepseek.com';
