import { spawnSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { WORKSPACE_ROOT } from './shared.mjs';
import { createPrePushBasePlan, resolvePrePushBaseRef } from './pre-push-base-ref.mjs';
import {
  decidePrePushVerification,
  formatLockfileFailureMessage,
  parsePrePushUpdates,
} from './pre-push-updates.mjs';
import { PREREQUISITE_ORDER, checkTreePrerequisites } from './tree-prerequisites.mjs';
import { CI_STAGES } from './ci-mirror-map.mjs';
import {
  findReusableVerification,
  isAutoGeneratedChurn,
  realDirtyLines,
} from './verification-receipt.mjs';
import {
  createPrePushChangeContext,
  createWorkRunMeasurementInput,
  createWorkRunMeasurementStep,
  resolvePrePushHookContext,
  runPrePushGate,
} from './pre-push-work-run.mjs';
import {
  reportPrePushBaseResolution,
  runPrePushVerification,
} from './pre-push-verification-execution.mjs';

export { createWorkRunMeasurementInput, runPrePushGate };
/**
 * The commands the REQUIRED `scans` context runs, mirrored locally.
 *
 * INFRA-069. `scans` is required on `protect-develop`, and this gate ran none of it: measured, a
 * change under a package's `src` selected ZERO scans, so the first thing that ever examined it was CI.
 * (The item counts 81 and the suite counts 99 today; the number the argument rests on is the zero.) The declared local mirror, `verify-like-ci`, was invoked by nothing at all.
 *
 * The item framed the open question as what the local gate should COST, on the reasoning that a slow
 * pre-push gets bypassed with `--no-verify`. Measured instead of debated: the scan suite is 6s and
 * the harness test suite 54s, against a CI round trip of five to six minutes. At a minute there is
 * nothing to trade off, so the whole suite runs and no subset had to be invented.
 *
 * FLAGS INCLUDED DELIBERATELY. `--skip dist --skip build-contracts` is what the workflow passes;
 * running MORE here than CI does would refuse pushes CI would accept, which is property 4 —
 * firing on correct work — and the fastest way to have a gate turned off. `pre-push-mirrors-ci-scans.test.mjs`
 * reads both sides so the two cannot drift silently.
 *
 * PROC-016: the scan stage runs the AFFECTED set (`--affected`) in the `pr` context, exactly as the
 * `scans` job does on a pull request. `--base` carries the base the classification already
 * resolved — the workflow writes `origin/$GITHUB_BASE_REF` in its place — so the diff the selection
 * is computed from is the diff the push is about; without a base the runner falls back to the full
 * suite and says so. The measured wall time of the stage is printed (TC-08).
 */
export const CI_BASE_REF_PLACEHOLDER = 'origin/$GITHUB_BASE_REF';

export const CI_SCANS_JOB_MIRROR = [
  ['pnpm', ['harness:test:contracts']],
  ['pnpm', ['harness:test:hermetic']],
  [
    'pnpm',
    [
      'harness:scan',
      '--',
      '--skip',
      'dist',
      '--skip',
      'build-contracts',
      '--affected',
      '--context',
      'pr',
      '--base',
      CI_BASE_REF_PLACEHOLDER,
    ],
  ],
];

/** The one `scans` step ci.yml gates on the `harness` classification (`needs.changes.outputs.harness`). */
const PATH_GATED_HARNESS_TEST = 'harness:test:hermetic';

/**
 * The local scans plan; an absent/unresolved verdict is deliberately harness-applicable.
 *
 * Exactly what the workflow gates, and no more. `harness:test:contracts` runs UNCONDITIONALLY in
 * ci.yml (INFRA-093): the repository-contract tests inspect product, docs and policy content, so a
 * diff that touches no harness file can still turn them red, and a mirror that skipped them on a
 * `harness: false` verdict would pass locally on a push CI refuses. Only the hermetic tier is
 * path-gated there — it reads nothing but `scripts/harness/**` and the files that decide how it
 * runs, which is what `classifyFiles` names `harness` — so only the hermetic tier is gated here
 * (PROC-016). A `false` verdict is a proof, not a default; anything else runs both tiers.
 * `baseRef` replaces the workflow's `origin/$GITHUB_BASE_REF`; with none, the `--base` pair is
 * dropped and the runner resolves (or fails closed to the full suite) on its own.
 */
export function createCiScansJobMirror(classification, { baseRef = null } = {}) {
  const harnessApplicable = classification?.harness !== false;
  return CI_SCANS_JOB_MIRROR.filter(
    ([, args]) => args[0] !== PATH_GATED_HARNESS_TEST || harnessApplicable,
  ).map(([command, args]) => [command, substituteBaseRef(args, baseRef)]);
}

function substituteBaseRef(args, baseRef) {
  const at = args.indexOf('--base');
  if (at === -1) return [...args];
  if (baseRef) return args.map((arg, i) => (i === at + 1 ? baseRef : arg));
  return args.filter((_, i) => i !== at && i !== at + 1);
}

function run(command, args) {
  const rendered = [command, ...args].join(' ');
  process.stdout.write(`> ${rendered}\n`);

  const result = spawnSync(command, args, {
    cwd: WORKSPACE_ROOT,
    stdio: 'inherit',
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function runGitQuiet(args) {
  return (
    spawnSync('git', args, {
      cwd: WORKSPACE_ROOT,
      stdio: 'ignore',
      encoding: 'utf8',
    }).status === 0
  );
}

/**
 * Run the same post-verdict guard used by Claude's Bash hook before the ordinary Git pre-push
 * verification. Git's hook is the boundary used by shells and subagents, so checking only the
 * Claude PreToolUse hook leaves an enforceable rule with an unenforced execution path.
 *
 * Any non-zero result is treated as a refusal (fail closed): the shell guard uses exit 2 for an
 * explicit block, while an unexpected exit is also unsafe to interpret as approval.
 */
export function runPostVerdictGuard({
  cwd = WORKSPACE_ROOT,
  spawn = spawnSync,
  script = path.join(WORKSPACE_ROOT, '.claude/hooks/pre-push-check.sh'),
} = {}) {
  const payload = JSON.stringify({
    tool_name: 'Bash',
    cwd,
    tool_input: { command: 'git push' },
  });
  const result = spawn('bash', [script], {
    cwd,
    input: payload,
    encoding: 'utf8',
    stdio: ['pipe', 'inherit', 'inherit'],
    env: { ...process.env, CLAUDE_PROJECT_DIR: cwd },
  });
  if (result.status !== 0) {
    process.stderr.write(
      '[pre-push] Blocked: post-verdict action-request guard did not approve this push.\n',
    );
    return false;
  }
  return true;
}

/**
 * Worktrees are ALLOWED (they power parallel sub-agent work — see git-branch.md § Git Worktree). This is the
 * non-blocking hygiene safeguard that replaces the old ban: prune administrative junk, then WARN about
 * locked/stale extra worktrees so left-behind ones surface — it never blocks the push.
 */
function pruneAndWarnStaleWorktrees() {
  spawnSync('git', ['worktree', 'prune'], { cwd: WORKSPACE_ROOT, encoding: 'utf8' });
  const result = spawnSync('git', ['worktree', 'list', '--porcelain'], {
    cwd: WORKSPACE_ROOT,
    encoding: 'utf8',
  });
  const entries = (result.stdout ?? '').trim().split('\n\n').filter(Boolean);
  const extra = entries.slice(1); // entry[0] is the main clone
  const locked = extra.filter((e) => /\nlocked/.test(`\n${e}`));
  if (locked.length > 0) {
    const paths = locked.map((e) => (e.match(/^worktree (.+)$/m) ?? [])[1] ?? '?').join('\n  ');
    process.stderr.write(
      `\n[worktree hygiene] ${locked.length} LOCKED worktree(s) present (not blocking):\n  ${paths}\n` +
        'If these are stale agent leftovers, clean up: git worktree remove <path> && git worktree prune\n\n',
    );
  }
}

function assertLockfileConsistency() {
  // pnpm 8's `--lockfile-only` rewrites pnpm-lock.yaml even with
  // --frozen-lockfile when the check passes, so the validation runs in a
  // throwaway copy of the manifests + lockfile (zero working-tree side effects).
  const stage = mkdtempSync(path.join(tmpdir(), 'robota-lockfile-check-'));
  try {
    const manifests = ['package.json', 'pnpm-workspace.yaml', 'pnpm-lock.yaml', '.npmrc'];
    for (const file of manifests) {
      const source = path.join(WORKSPACE_ROOT, file);
      if (existsSync(source)) copyFileSync(source, path.join(stage, file));
    }
    for (const family of ['packages', 'apps']) {
      const familyDir = path.join(WORKSPACE_ROOT, family);
      if (!existsSync(familyDir)) continue;
      for (const entry of readdirSync(familyDir, { withFileTypes: true })) {
        if (!entry.isDirectory()) continue;
        const manifest = path.join(familyDir, entry.name, 'package.json');
        if (!existsSync(manifest)) continue;
        const targetDir = path.join(stage, family, entry.name);
        mkdirSync(targetDir, { recursive: true });
        copyFileSync(manifest, path.join(targetDir, 'package.json'));
      }
    }
    const result = spawnSync('pnpm', ['install', '--frozen-lockfile', '--lockfile-only'], {
      cwd: stage,
      stdio: 'ignore',
      encoding: 'utf8',
    });
    if (result.status !== 0) {
      process.stderr.write(formatLockfileFailureMessage());
      process.exit(1);
    }
  } finally {
    rmSync(stage, { recursive: true, force: true });
  }
}

// The churn set moved to `verification-receipt.mjs` under INFRA-101 so that this gate and the receipt
// it reuses agree on what "clean" means. Keeping a second copy here is what starved the receipt:
// this file excepted the churn, the receipt writer did not, and no receipt was ever written.
const isEvalsAutoChurn = isAutoGeneratedChurn;

function assertCleanWorkingTree() {
  const result = spawnSync('git', ['status', '--porcelain'], {
    cwd: WORKSPACE_ROOT,
    encoding: 'utf8',
  });
  const lines = (result.stdout ?? '')
    .split('\n')
    .map((l) => l.trimEnd())
    .filter(Boolean);
  // XY status codes: first char = staged, second char = unstaged.
  // '??' = untracked. We block on any modified/staged file but not on
  // untracked files (those are handled by .gitignore discipline).
  const tracked = lines.filter((l) => l.slice(0, 2) !== '??');
  const tolerated = tracked.filter(isEvalsAutoChurn);
  const dirty = tracked.filter((l) => !isEvalsAutoChurn(l));
  if (tolerated.length > 0 && dirty.length === 0) {
    process.stdout.write(
      '▶ tolerating auto-generated evals churn (not blocking push):\n' +
        tolerated.map((l) => `  ${l}`).join('\n') +
        '\n',
    );
  }
  if (dirty.length > 0) {
    process.stderr.write(
      '\n[BLOCKED] Uncommitted changes detected — push blocked.\n' +
        'Commit or discard all modified/staged files before pushing:\n\n' +
        dirty.map((l) => `  ${l}`).join('\n') +
        '\n\nSee .agents/rules/git-branch.md "Clean Working Tree" rule.\n\n',
    );
    process.exit(1);
  }
}

function hasWorkingTreeChanges() {
  // Same definition of "clean" as the receipt writer (INFRA-101). Auto-generated churn does not count;
  // everything else does, and a git failure is treated as dirty because an unknown tree is not clean.
  try {
    return realDirtyLines(WORKSPACE_ROOT).length > 0;
  } catch {
    return true;
  }
}

function readPrePushInput() {
  if (process.stdin.isTTY) {
    return { input: '', provided: false };
  }

  try {
    const input = readFileSync(0, 'utf8');
    return { input, provided: input.trim().length > 0 };
  } catch {
    return { input: '', provided: true };
  }
}

function readGitValue(args) {
  const result = spawnSync('git', args, {
    cwd: WORKSPACE_ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  });
  return result.status === 0 ? result.stdout.trim() : '';
}

function resolvePrePushMode(value) {
  const mode = value?.trim() || 'fast';
  if (mode !== 'fast' && mode !== 'full') {
    throw new Error('HARNESS_PRE_PUSH_MODE must be one of: fast, full');
  }
  return mode;
}

/**
 * HARNESS-058: this gate runs `pnpm harness:verify` and then `pnpm cli:dev --version`, and both read
 * build output it never produces. In a fresh worktree the smoke check died on
 * `Cannot find module '…/packages/agent-command-workflows/node_modules/@robota-sdk/dag-core/dist/node/index.js'`
 * — a message that reads like a broken import in the change being pushed. It is not a verdict on the
 * change; it is an unprepared tree, and it says so now. The push is still blocked: naming the
 * prerequisite is what changed, not whether the gate holds.
 *
 * Called only from the verifying branch of `runPrePushGate` — see the ordering note there.
 */
/**
 * Which prerequisites a push owes, from the same classifier CI's `changes` job reads (PROC-016).
 * `build-output` is owed only when PRODUCT code changed — a package or app source the verification
 * will build and test. A harness-only or docs-only change reads no `dist/`, and demanding 81
 * packages' build output for it (88 s and ~2 GB in a fresh worktree, measured on INFRA-136) was the
 * single largest cost of the L1 lane. `verify-like-ci` already decides the same question from the
 * plan (`planRequiresPackageDist`); this is that decision at the pre-push gate. Fail-closed: an
 * unclassifiable change (`product` not `false`) owes everything.
 */
export function prerequisitesFor(classification) {
  return classification?.product === false ? ['install'] : PREREQUISITE_ORDER;
}

function assertTreePrerequisitesFor(classification) {
  const required = prerequisitesFor(classification);
  const result = checkTreePrerequisites('the pre-push gate', WORKSPACE_ROOT, required);
  if (result.ok) {
    if (required.length < PREREQUISITE_ORDER.length)
      process.stdout.write(
        '▶ build output not required: no product code changed (harness/docs-only push)\n',
      );
    return;
  }
  process.stderr.write(result.message);
  process.exit(1);
}

/**
 * The gate's step ORDER, stated once and exported so a test can assert the sequence itself.
 *
 * HARNESS-058, second face. `assertTreePrerequisites` used to run third — before
 * `decidePrePushVerification` had decided whether anything would be verified at all. But two kinds
 * of push run NO verification: a delete-only push, and a re-push whose tree has no content delta
 * from its base. Neither reads `node_modules` or `dist`, and both were refused in a fresh worktree,
 * demanding `pnpm install && pnpm build` for a push with nothing to check — in exactly the
 * parallel-subagent-in-a-fresh-worktree configuration this item exists to serve.
 *
 * A prerequisite is owed only by work that is actually going to happen, so it is asserted AFTER the
 * decision to verify. The steps are INJECTED rather than called directly because the defect was an
 * ordering defect: a test asserting only "a delete-only push is allowed" would go green again if the
 * assertion moved back ahead of the decision for some unrelated reason.
 * The injected plan also keeps the existing fast/full verification selection unchanged.
 */
function createPrePushRuntime() {
  const prePushInput = readPrePushInput();
  const updates = parsePrePushUpdates(prePushInput.input);
  const currentBranch = readGitValue(['symbolic-ref', '--quiet', '--short', 'HEAD']);
  const headOid = readGitValue(['rev-parse', 'HEAD^{commit}']);
  const { pushSubject, hookInputProvided } = resolvePrePushHookContext({
    prePushInput,
    updates,
    currentBranch,
    headOid,
    env: process.env,
  });
  const baseResolution = resolvePrePushBaseRef({
    updates,
    hookInputProvided,
    currentBranch,
    headOid,
    pushRemoteName: process.env.HARNESS_PRE_PUSH_REMOTE_NAME ?? null,
    pushRemoteUrl: process.env.HARNESS_PRE_PUSH_REMOTE_URL ?? null,
    originUrl: readGitValue(['remote', 'get-url', 'origin']),
    explicitBaseRef: process.env.HARNESS_BASE_REF ?? null,
    env: process.env,
    pushSubject,
  });
  const basePlan = createPrePushBasePlan(baseResolution);
  const baseRef = basePlan.baseRef;
  const baseArgs = basePlan.baseArgs;
  const prePushMode = resolvePrePushMode(process.env.HARNESS_PRE_PUSH_MODE);
  const scopeExpansionArgs = prePushMode === 'fast' ? ['--skip-dependent-scopes'] : [];
  const { subjectRef, changeClassification } = createPrePushChangeContext({
    baseRef: basePlan.classificationBaseRef,
    pushSubject,
    headOid,
    root: WORKSPACE_ROOT,
  });
  return {
    updates,
    pushSubject,
    baseResolution,
    basePlan,
    baseRef,
    baseArgs,
    prePushMode,
    scopeExpansionArgs,
    subjectRef,
    changeClassification,
  };
}

export function createPrePushSteps() {
  const runtime = createPrePushRuntime();

  return {
    pruneAndWarnStaleWorktrees,
    assertCleanWorkingTree,
    assertLockfileConsistency,
    assertTreePrerequisites: () => assertTreePrerequisitesFor(runtime.changeClassification),
    reportBaseResolution: () => reportPrePushBaseResolution(runtime),
    decideVerification: () =>
      decidePrePushVerification({
        updates: runtime.updates,
        baseRef: runtime.basePlan.decisionBaseRef,
        treeMatchesBase:
          runtime.basePlan.decisionBaseRef && !hasWorkingTreeChanges()
            ? runGitQuiet([
                'diff',
                '--quiet',
                runtime.basePlan.decisionBaseRef,
                runtime.subjectRef,
                '--',
              ])
            : false,
      }),
    validateWorkRunMeasurement: createWorkRunMeasurementStep({
      root: WORKSPACE_ROOT,
      baseRef: runtime.basePlan.classificationBaseRef ?? runtime.baseRef,
      pushSubject: runtime.pushSubject,
    }),
    findReusableReceipt: () =>
      findReusableVerification({
        baseRef: runtime.basePlan.receiptBaseRef,
        stages: CI_STAGES.map((stage) => stage.name),
        updates: runtime.updates,
        root: WORKSPACE_ROOT,
      }),
    reportReceiptReused: (receipt) =>
      process.stdout.write(
        `▶ exact verify-like-ci receipt reused for ${receipt.headCommit.slice(0, 12)}; pre-push verification is already covered\n`,
      ),
    reportSkipped: (reason) =>
      process.stdout.write(`▶ scoped pre-push verification skipped: ${reason}\n`),
    runVerification: () =>
      runPrePushVerification(runtime, { run, createMirror: createCiScansJobMirror }),
  };
}

// Guarded so a test can import `runPrePushGate` without running the gate against its own checkout.
if (path.resolve(process.argv[1] ?? '') === path.resolve(import.meta.filename)) {
  if (!runPostVerdictGuard()) process.exit(2);
  runPrePushGate(createPrePushSteps());
}
