import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const RECEIPT_SCHEMA_VERSION = 1;
const RECEIPT_FILE = 'robota-verification/verify-like-ci.json';
const OWNER_FILES = [
  '.github/workflows/ci.yml',
  '.lintstagedrc.json',
  'package.json',
  'scripts/harness/with-repo-lock.sh',
];

function normalizedIdentity(identity) {
  if (!identity || typeof identity !== 'object') return null;
  const scalarFields = [
    'headCommit',
    'headTree',
    'baseCommit',
    'profile',
    'nodeVersion',
    'pnpmVersion',
    'lockfileHash',
    'ownerFingerprint',
  ];
  if (scalarFields.some((field) => typeof identity[field] !== 'string' || !identity[field])) {
    return null;
  }
  if (
    !Array.isArray(identity.stages) ||
    identity.stages.some((stage) => typeof stage !== 'string')
  ) {
    return null;
  }
  return Object.fromEntries([
    ...scalarFields.map((field) => [field, identity[field]]),
    ['stages', [...identity.stages]],
  ]);
}

export function createVerificationReceipt(identity, verifiedAt = new Date().toISOString()) {
  const normalized = normalizedIdentity(identity);
  if (!normalized)
    throw new Error('Cannot create a verification receipt from an invalid identity.');
  return {
    schemaVersion: RECEIPT_SCHEMA_VERSION,
    status: 'pass',
    verifiedAt,
    identity: normalized,
  };
}

export function receiptMatches(receipt, expectedIdentity) {
  if (!receipt || receipt.schemaVersion !== RECEIPT_SCHEMA_VERSION || receipt.status !== 'pass') {
    return false;
  }
  const actual = normalizedIdentity(receipt.identity);
  const expected = normalizedIdentity(expectedIdentity);
  return Boolean(actual && expected && JSON.stringify(actual) === JSON.stringify(expected));
}

export function shouldWriteFullReceipt({ exitCode, clean, selectedStages, requiredStages }) {
  return (
    exitCode === 0 &&
    clean === true &&
    Array.isArray(selectedStages) &&
    Array.isArray(requiredStages) &&
    JSON.stringify(selectedStages) === JSON.stringify(requiredStages)
  );
}

function run(command, args, root) {
  const result = spawnSync(command, args, { cwd: root, encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(' ')} failed: ${result.stderr?.trim()}`);
  }
  return result.stdout.trim();
}

function listOwnerFiles(root) {
  const files = [...OWNER_FILES];
  const harnessRoot = path.join(root, 'scripts/harness');
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === '__tests__' || entry.name === 'node_modules') continue;
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(absolute);
      else if (entry.name.endsWith('.mjs')) files.push(path.relative(root, absolute));
    }
  };
  walk(harnessRoot);
  return [...new Set(files)].sort();
}

function hashFiles(root, files) {
  const hash = createHash('sha256');
  for (const file of files) {
    hash.update(file);
    hash.update('\0');
    hash.update(readFileSync(path.join(root, file)));
    hash.update('\0');
  }
  return hash.digest('hex');
}

/**
 * Auto-generated learning artifacts that `harness:scan` REWRITES on every run and that
 * `.husky/pre-commit` refuses to let you stage (git-branch.md — regenerated churn, not authored
 * content). They are tracked deliverables, so they are neither gitignorable nor committable, and they
 * are dirty again the moment any scan runs.
 *
 * This set is the SINGLE OWNER of "which dirt does not count". Before INFRA-101 the definition existed
 * three times — `assertCleanWorkingTree` in `pre-push.mjs` excepted this churn, while
 * `hasWorkingTreeChanges` there and `isCleanTree` here did not. The consequence was not cosmetic:
 * `verify-like-ci` dirties the tree by running, then `writeVerificationReceipt` declined to write
 * because the tree was dirty, so the receipt was NEVER produced and every push re-ran the full
 * ~15-minute gate. Five consecutive PASS runs left `readVerificationReceipt()` at `null`.
 */
export const AUTO_GENERATED_CHURN = new Set([
  '.agents/evals/lessons/auto-lessons.md',
  '.agents/evals/lessons/weekly-digest.md',
]);

/** True when a `git status --porcelain` line names a file in {@link AUTO_GENERATED_CHURN}. */
export function isAutoGeneratedChurn(statusLine) {
  return AUTO_GENERATED_CHURN.has(statusLine.slice(3).trim());
}

/**
 * `git status --porcelain` lines that are NOT auto-generated churn. Exported so a caller can both
 * decide and report — a caller that only gets a boolean has to re-run git to say what was dirty.
 */
export function realDirtyLines(root) {
  // NOT via run(): it trims, and in porcelain output the LEADING space is the staged-status column,
  // so trimming shifts the first line by one and `slice(3)` then reads the wrong substring. Caught by
  // the fixture below asserting churn-only dirt is clean.
  const result = spawnSync('git', ['status', '--porcelain', '--untracked-files=all'], {
    cwd: root,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    throw new Error(`git status failed: ${result.stderr?.trim()}`);
  }
  return result.stdout.split('\n').filter((line) => line !== '' && !isAutoGeneratedChurn(line));
}

/**
 * Clean ENOUGH to stand behind a receipt: no dirt except the churn above. Anything a human or a build
 * changed still makes the tree unclean — the exemption is narrow and named, not a general tolerance.
 */
export function isCleanTree(root) {
  return realDirtyLines(root).length === 0;
}

export function verificationReceiptPath(root) {
  const commonDir = run('git', ['rev-parse', '--path-format=absolute', '--git-common-dir'], root);
  return path.join(commonDir, RECEIPT_FILE);
}

export function computeVerificationIdentity({ baseRef, stages, root }) {
  return {
    headCommit: run('git', ['rev-parse', 'HEAD^{commit}'], root),
    headTree: run('git', ['rev-parse', 'HEAD^{tree}'], root),
    baseCommit: run('git', ['rev-parse', `${baseRef}^{commit}`], root),
    profile: 'verify-like-ci/full',
    stages: [...stages],
    nodeVersion: process.version,
    pnpmVersion: run('pnpm', ['--version'], root),
    lockfileHash: hashFiles(root, ['pnpm-lock.yaml']),
    ownerFingerprint: hashFiles(root, listOwnerFiles(root)),
  };
}

export function readVerificationReceipt(root) {
  try {
    return JSON.parse(readFileSync(verificationReceiptPath(root), 'utf8'));
  } catch {
    return null;
  }
}

export function writeVerificationReceipt({ baseRef, stages, root }) {
  const dirty = realDirtyLines(root);
  if (dirty.length > 0) {
    // Silence is not success: the caller reports PASS, so a receipt that was not written has to say
    // so here or the operator only learns of it when the next push spends fifteen minutes again.
    return {
      written: false,
      reason: `working tree is not clean: ${dirty.join(', ')}`,
    };
  }
  const target = verificationReceiptPath(root);
  const receipt = createVerificationReceipt(computeVerificationIdentity({ baseRef, stages, root }));
  mkdirSync(path.dirname(target), { recursive: true });
  const temporary = `${target}.${process.pid}.tmp`;
  writeFileSync(temporary, `${JSON.stringify(receipt, null, 2)}\n`, 'utf8');
  renameSync(temporary, target);
  return { written: true, target, receipt };
}

export function pushedObjectsMatchVerifiedHead(updates, headCommit) {
  return (updates ?? [])
    .filter((update) => update.localRef !== '(delete)' && !/^0{40,64}$/u.test(update.localObjectId))
    .every((update) => update.localObjectId === headCommit);
}

export function findReusableVerification({ baseRef, stages, updates, root }) {
  try {
    if (!isCleanTree(root)) return { reusable: false, reason: 'working tree is not clean' };
    const expected = computeVerificationIdentity({ baseRef, stages, root });
    if (!pushedObjectsMatchVerifiedHead(updates, expected.headCommit)) {
      return { reusable: false, reason: 'pushed object differs from verified HEAD' };
    }
    const receipt = readVerificationReceipt(root);
    return receiptMatches(receipt, expected)
      ? { reusable: true, headCommit: expected.headCommit }
      : { reusable: false, reason: 'no exact full-gate receipt' };
  } catch (error) {
    return { reusable: false, reason: error?.message ?? String(error) };
  }
}

function argValues(argv, flag) {
  const values = [];
  for (let index = 0; index < argv.length; index += 1) {
    if (argv[index] === flag && argv[index + 1]) values.push(argv[index + 1]);
  }
  return values;
}

if (path.resolve(process.argv[1] ?? '') === path.resolve(import.meta.filename)) {
  const baseRefIndex = process.argv.indexOf('--base-ref');
  const baseRef = baseRefIndex >= 0 ? process.argv[baseRefIndex + 1] : null;
  const stages = argValues(process.argv.slice(2), '--stage');
  if (!baseRef || stages.length === 0) {
    process.stderr.write('usage: verification-receipt.mjs --base-ref <ref> --stage <name>...\n');
    process.exitCode = 2;
  } else {
    const result = writeVerificationReceipt({ baseRef, stages, root: process.cwd() });
    process.stdout.write(
      result.written
        ? `verification receipt written: ${result.target}\n`
        : `verification receipt not written: ${result.reason}\n`,
    );
    if (!result.written) process.exitCode = 1;
  }
}
