// Shared clean-tree helpers retained for scan receipts and other local checks.
export {
  AUTO_GENERATED_CHURN,
  isAutoGeneratedChurn,
  isCleanTree,
  realDirtyLines,
} from './verification-receipt-storage.mjs';
