import path from 'node:path';

import { runVerificationCommand } from './verification-receipt-command.mjs';
import {
  computeVerificationIdentity,
  createVerificationReceipt,
  receiptMatches,
  shouldWriteFullReceipt,
} from './verification-receipt-identity.mjs';
import {
  AUTO_GENERATED_CHURN,
  isAutoGeneratedChurn,
  isCleanTree,
  readVerificationReceipt,
  realDirtyLines,
  verificationReceiptPath,
  writeVerificationReceipt,
} from './verification-receipt-storage.mjs';
import {
  isWorkRunReceiptClosure,
  verificationHeadCandidates,
} from './verification-receipt-work-run-closure.mjs';

export {
  AUTO_GENERATED_CHURN,
  computeVerificationIdentity,
  createVerificationReceipt,
  isAutoGeneratedChurn,
  isCleanTree,
  isWorkRunReceiptClosure,
  readVerificationReceipt,
  realDirtyLines,
  receiptMatches,
  shouldWriteFullReceipt,
  verificationReceiptPath,
  writeVerificationReceipt,
};

export function pushedObjectsMatchVerifiedHead(updates, headCommit) {
  return (updates ?? [])
    .filter((update) => update.localRef !== '(delete)' && !/^0{40,64}$/u.test(update.localObjectId))
    .every((update) => update.localObjectId === headCommit);
}

export function findReusableVerification({ baseRef, stages, updates, root }) {
  try {
    if (!isCleanTree(root)) return { reusable: false, reason: 'working tree is not clean' };
    const currentHead = runVerificationCommand('git', ['rev-parse', 'HEAD^{commit}'], root);
    if (!pushedObjectsMatchVerifiedHead(updates, currentHead)) {
      return { reusable: false, reason: 'pushed object differs from verified HEAD' };
    }
    const receipt = readVerificationReceipt(root);
    for (const headRef of verificationHeadCandidates(root, currentHead)) {
      const expected = computeVerificationIdentity({ baseRef, stages, root, headRef });
      if (receiptMatches(receipt, expected)) {
        return { reusable: true, headCommit: currentHead, verifiedHeadCommit: headRef };
      }
    }
    return { reusable: false, reason: 'no exact full-gate receipt' };
  } catch (error) {
    return { reusable: false, reason: error?.message ?? String(error) };
  }
}

function argValues(argv, flag) {
  const values = [];
  for (let index = 0; index < argv.length; index += 1) {
    if (argv[index] === flag && argv[index + 1]) values.push(argv[index + 1]);
  }
  return values;
}

function runCli(argv) {
  const baseRefIndex = argv.indexOf('--base-ref');
  const baseRef = baseRefIndex >= 0 ? argv[baseRefIndex + 1] : null;
  const stages = argValues(argv, '--stage');
  if (!baseRef || stages.length === 0) {
    process.stderr.write('usage: verification-receipt.mjs --base-ref <ref> --stage <name>...\n');
    process.exitCode = 2;
    return;
  }
  const result = writeVerificationReceipt({ baseRef, stages, root: process.cwd() });
  process.stdout.write(
    result.written
      ? `verification receipt written: ${result.target}\n`
      : `verification receipt not written: ${result.reason}\n`,
  );
  if (!result.written) process.exitCode = 1;
}

if (path.resolve(process.argv[1] ?? '') === path.resolve(import.meta.filename)) {
  runCli(process.argv.slice(2));
}
