// harness-coverage: verification-receipt-command.mjs
// harness-coverage: verification-receipt-identity.mjs
// harness-coverage: verification-receipt-storage.mjs
// harness-coverage: verification-receipt-work-run-closure.mjs
// harness-coverage: bounded-git-status.mjs
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { afterAll, describe, expect, it, vi } from 'vitest';

import { makeTemp } from './make-temp.mjs';

import {
  AUTO_GENERATED_CHURN,
  computeVerificationIdentity,
  createVerificationReceipt,
  findReusableVerification,
  isAutoGeneratedChurn,
  isCleanTree,
  isWorkRunReceiptClosure,
  pushedObjectsMatchVerifiedHead,
  realDirtyLines,
  receiptMatches,
  shouldWriteFullReceipt,
  writeVerificationReceipt,
} from '../verification-receipt.mjs';
import { runVerificationCommand } from '../verification-receipt-command.mjs';
import { executableFingerprint } from '../verification-receipt-identity.mjs';
import { boundedGitStatus } from '../bounded-git-status.mjs';
import {
  appendWorkRunEvent,
  createInitialWorkRun,
  projectWorkRunDurations,
} from '../work-run-contract.mjs';

const REPOSITORY_PACKAGE_MANAGER = JSON.parse(
  readFileSync(path.resolve(import.meta.dirname, '../../..', 'package.json'), 'utf8'),
).packageManager;

const identity = {
  headCommit: 'head-a',
  headTree: 'tree-a',
  baseCommit: 'base-a',
  profile: 'verify-like-ci/full',
  stages: ['format-check', 'harness-self-test'],
  nodeVersion: 'v22.14.0',
  pnpmVersion: '8.15.4',
  platform: 'darwin',
  architecture: 'arm64',
  osRelease: '25.6.0',
  gitIdentity: '{"path":"/usr/bin/git","sha256":"git-a","version":"git version a"}',
  awkIdentity: '{"path":"/usr/bin/awk","sha256":"awk-a","probe":"awk-v1"}',
  realpathIdentity:
    '{"path":"/usr/bin/realpath","sha256":"realpath-a","probe":"/usr/bin/realpath"}',
  lockfileHash: 'lock-a',
  ownerFingerprint: 'owners-a',
};

describe('exact verification receipts', () => {
  it('matches only an identical successful full-gate identity', () => {
    const receipt = createVerificationReceipt(identity);
    expect(receiptMatches(receipt, identity)).toBe(true);

    for (const [field, value] of [
      ['headCommit', 'head-b'],
      ['headTree', 'tree-b'],
      ['baseCommit', 'base-b'],
      ['profile', 'pre-push/fast'],
      ['nodeVersion', 'v24.0.0'],
      ['pnpmVersion', '9.0.0'],
      ['platform', 'linux'],
      ['architecture', 'x64'],
      ['osRelease', '6.8.0'],
      ['gitIdentity', '{"path":"/usr/bin/git","sha256":"git-b"}'],
      ['awkIdentity', '{"path":"/usr/bin/awk","sha256":"awk-b"}'],
      ['realpathIdentity', '{"path":"/usr/bin/realpath","sha256":"realpath-b"}'],
      ['lockfileHash', 'lock-b'],
      ['ownerFingerprint', 'owners-b'],
    ]) {
      expect(receiptMatches(receipt, { ...identity, [field]: value }), field).toBe(false);
    }
    expect(receiptMatches(receipt, { ...identity, stages: ['format-check'] })).toBe(false);
  });

  it('measures the exact OS and path-resolved tool implementations deterministically', () => {
    const root = path.resolve(import.meta.dirname, '../../..');
    const input = { baseRef: 'HEAD', stages: ['full'], root };
    const first = computeVerificationIdentity(input);
    const second = computeVerificationIdentity(input);

    expect(second).toEqual(first);
    expect(first).toMatchObject({
      platform: process.platform,
      architecture: process.arch,
    });
    expect(first.osRelease).toMatch(/\S/u);
    for (const field of ['gitIdentity', 'awkIdentity', 'realpathIdentity']) {
      const tool = JSON.parse(first[field]);
      expect(tool.path).toMatch(/^\//u);
      expect(tool.sha256).toMatch(/^[a-f0-9]{64}$/u);
      expect(tool.probe ?? tool.version).toMatch(/\S/u);
    }
  });

  it('fails closed when a verification identity command exceeds its bound', () => {
    expect(() =>
      runVerificationCommand(process.execPath, ['-e', 'setTimeout(() => {}, 500)'], process.cwd(), {
        timeoutMs: 25,
      }),
    ).toThrow(/timed out after 25ms/u);
  });

  it('treats missing, malformed, partial, failed, and unknown-version receipts as misses', () => {
    expect(receiptMatches(null, identity)).toBe(false);
    expect(receiptMatches({}, identity)).toBe(false);
    expect(
      receiptMatches({ ...createVerificationReceipt(identity), status: 'fail' }, identity),
    ).toBe(false);
    expect(
      receiptMatches({ ...createVerificationReceipt(identity), schemaVersion: 999 }, identity),
    ).toBe(false);
    for (const field of [
      'platform',
      'architecture',
      'osRelease',
      'gitIdentity',
      'awkIdentity',
      'realpathIdentity',
    ]) {
      const incomplete = createVerificationReceipt(identity);
      delete incomplete.identity[field];
      expect(receiptMatches(incomplete, identity), field).toBe(false);
    }
  });

  it('fails closed when a required tool cannot be resolved from PATH', () => {
    const originalPath = process.env.PATH;
    process.env.PATH = '';
    try {
      expect(() =>
        computeVerificationIdentity({
          baseRef: 'HEAD',
          stages: ['full'],
          root: path.resolve(import.meta.dirname, '../../..'),
        }),
      ).toThrow(/command -v/u);
    } finally {
      process.env.PATH = originalPath;
    }
  });

  it('fingerprints one opened descriptor instead of checking and rereading a path', () => {
    const descriptor = 17;
    const contents = Buffer.from('stable executable bytes');
    const io = {
      realpathSync: vi.fn(() => '/resolved/tool'),
      openSync: vi.fn(() => descriptor),
      fstatSync: vi.fn(() => ({ isFile: () => true, size: contents.length })),
      readFileSync: vi.fn(() => contents),
      closeSync: vi.fn(),
    };

    expect(executableFingerprint('/path/tool', io)).toEqual({
      path: '/resolved/tool',
      sha256: createHash('sha256').update(contents).digest('hex'),
    });
    expect(io.openSync).toHaveBeenCalledWith('/resolved/tool', 'r');
    expect(io.fstatSync).toHaveBeenCalledWith(descriptor);
    expect(io.readFileSync).toHaveBeenCalledWith(descriptor);
    expect(io.closeSync).toHaveBeenCalledWith(descriptor);
  });

  it('closes the descriptor and fails closed when the opened executable becomes unreadable', () => {
    const failure = Object.assign(new Error('executable disappeared'), { code: 'ENOENT' });
    const closeSync = vi.fn();

    expect(() =>
      executableFingerprint('/path/tool', {
        realpathSync: () => '/resolved/tool',
        openSync: () => 23,
        fstatSync: () => ({ isFile: () => true, size: 12 }),
        readFileSync: () => {
          throw failure;
        },
        closeSync,
      }),
    ).toThrow(failure);
    expect(closeSync).toHaveBeenCalledWith(23);
  });

  it('writes evidence only for a complete clean successful stage set', () => {
    const complete = {
      exitCode: 0,
      clean: true,
      selectedStages: ['a', 'b'],
      requiredStages: ['a', 'b'],
    };
    expect(shouldWriteFullReceipt(complete)).toBe(true);
    expect(shouldWriteFullReceipt({ ...complete, clean: false })).toBe(false);
    expect(shouldWriteFullReceipt({ ...complete, exitCode: 1 })).toBe(false);
    expect(shouldWriteFullReceipt({ ...complete, selectedStages: ['a'] })).toBe(false);
  });

  it('reuses evidence only when every non-delete pushed object is the verified HEAD', () => {
    const update = (localObjectId, localRef = 'refs/heads/feature') => ({
      localRef,
      localObjectId,
    });
    expect(pushedObjectsMatchVerifiedHead([update('head-a')], 'head-a')).toBe(true);
    expect(pushedObjectsMatchVerifiedHead([update('head-b')], 'head-a')).toBe(false);
    expect(
      pushedObjectsMatchVerifiedHead(
        [update('head-a'), update('0'.repeat(40), '(delete)')],
        'head-a',
      ),
    ).toBe(true);
  });

  it('permits only an exact work-run receipt-only child as a verification closure', () => {
    expect(isWorkRunReceiptClosure(['A\t.agents/evals/work-runs/run-1/g0-r0.json'])).toBe(true);
    expect(
      isWorkRunReceiptClosure([
        'A\t.agents/evals/work-runs/run-1/g0-r0.json',
        'M\tpackages/core/src/index.ts',
      ]),
    ).toBe(false);
    expect(isWorkRunReceiptClosure(['M\t.agents/evals/work-runs/run-1/g0-r0.json'])).toBe(false);
    expect(isWorkRunReceiptClosure(['A\treceipt.json'])).toBe(false);
  });
});

describe('auto-generated churn is the only dirt that does not count (INFRA-101)', () => {
  // `git status --porcelain` puts the staged column in position 0, so an unstaged edit begins with a
  // SPACE. Every fixture here keeps it — dropping it is the bug this suite exists to catch.
  const unstaged = (p) => ` M ${p}`;
  const staged = (p) => `M  ${p}`;

  it('recognises each churn file, in the exact form git emits', () => {
    expect([...AUTO_GENERATED_CHURN]).toEqual([
      '.agents/evals/lessons/auto-lessons.md',
      '.agents/evals/lessons/weekly-digest.md',
    ]);
    for (const file of AUTO_GENERATED_CHURN) {
      expect(isAutoGeneratedChurn(unstaged(file))).toBe(true);
      expect(isAutoGeneratedChurn(staged(file))).toBe(true);
    }
  });

  it('does not except anything else, including its own directory', () => {
    expect(isAutoGeneratedChurn(unstaged('packages/agent-cli/src/cli.ts'))).toBe(false);
    expect(isAutoGeneratedChurn(unstaged('.agents/evals/lessons/hand-written.md'))).toBe(false);
    expect(isAutoGeneratedChurn(unstaged('.agents/evals/README.md'))).toBe(false);
  });

  it('is not fooled by a path that merely ends with a churn filename', () => {
    expect(isAutoGeneratedChurn(unstaged('vendor/.agents/evals/lessons/auto-lessons.md'))).toBe(
      false,
    );
  });

  it('needs the leading status column — a trimmed line must NOT match', () => {
    // The defect this asserts against: reading porcelain output through a helper that trims makes the
    // FIRST line lose its leading space, so `slice(3)` reads one character into the path and the
    // churn stops being recognised. That is what starved the receipt for five consecutive runs.
    expect(isAutoGeneratedChurn('.agents/evals/lessons/auto-lessons.md')).toBe(false);
    expect(isAutoGeneratedChurn('M .agents/evals/lessons/auto-lessons.md')).toBe(false);
  });
});

describe('verification receipt reuse across the measured closure commit', () => {
  const roots = [];

  afterAll(() => {
    for (const root of roots) rmSync(root, { recursive: true, force: true });
  });

  function fixture() {
    const root = makeTemp('verification-closure-');
    roots.push(root);
    const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
    git('init', '--quiet', '-b', 'develop');
    git('config', 'user.email', 'test@example.com');
    git('config', 'user.name', 'test');
    git('config', 'commit.gpgsign', 'false');
    for (const [file, contents] of [
      ['.github/workflows/ci.yml', 'name: ci\n'],
      ['.lintstagedrc.json', '{}\n'],
      [
        'package.json',
        `${JSON.stringify({ name: 'fixture', packageManager: REPOSITORY_PACKAGE_MANAGER })}\n`,
      ],
      ['pnpm-lock.yaml', 'lockfileVersion: 6\n'],
      ['scripts/harness/with-repo-lock.sh', '#!/bin/sh\n'],
      ['scripts/harness/owner.mjs', 'export const owner = true;\n'],
      ['source.txt', 'base\n'],
    ]) {
      const absolute = path.join(root, file);
      mkdirSync(path.dirname(absolute), { recursive: true });
      writeFileSync(absolute, contents);
    }
    git('add', '-A');
    git('commit', '--quiet', '-m', 'base');
    git('branch', 'verification-base');
    writeFileSync(path.join(root, 'source.txt'), 'measured\n');
    git('add', 'source.txt');
    git('commit', '--quiet', '-m', 'feat: measured');
    const verifiedHead = git('rev-parse', 'HEAD');
    expect(
      writeVerificationReceipt({
        baseRef: 'verification-base',
        stages: ['full'],
        root,
      }).written,
    ).toBe(true);

    return { git, root, verifiedHead };
  }

  function includedReceipt(headCommit, runId = 'run-1') {
    let run = createInitialWorkRun({
      runId,
      branch: 'feature',
      at: '2026-08-30T00:00:00.000Z',
    });
    run = appendWorkRunEvent(run, {
      type: 'work.bound',
      at: '2026-08-30T00:00:01.000Z',
      data: { workId: 'TASK-1', lane: 'L2', workKind: 'implementation' },
    });
    run = appendWorkRunEvent(run, {
      type: 'work.started',
      at: '2026-08-30T00:00:02.000Z',
    });
    run = appendWorkRunEvent(run, {
      type: 'work.ready',
      at: '2026-08-30T00:00:03.000Z',
      data: { generation: 0, revision: 0 },
    });
    return {
      schemaVersion: 1,
      disposition: 'included',
      runId,
      generation: 0,
      revision: 0,
      identity: {
        repository: 'woojubb/robota',
        branch: 'feature',
        baseCommit: 'b'.repeat(40),
        headCommit,
        headTree: 'c'.repeat(40),
        commitOids: [headCommit],
        trailerDigest: 'd'.repeat(64),
        ownerFingerprint: 'e'.repeat(64),
      },
      cohort: { key: 'L2/implementation', lane: 'L2', workKind: 'implementation' },
      events: run.events,
      durations: projectWorkRunDurations(run.events),
      timestamps: {
        claimedAt: run.events[0].at,
        readyAt: run.events.at(-1).at,
      },
    };
  }

  function commitClosure(
    fixtureValue,
    {
      contents = includedReceipt(fixtureValue.verifiedHead),
      message = 'chore: close work run\n\nWork-Run: run-1\nWork-Receipt: g0-r0',
      receiptPath = '.agents/evals/work-runs/run-1/g0-r0.json',
    } = {},
  ) {
    const absolute = path.join(fixtureValue.root, receiptPath);
    mkdirSync(path.dirname(absolute), { recursive: true });
    writeFileSync(
      absolute,
      typeof contents === 'string' ? contents : `${JSON.stringify(contents, null, 2)}\n`,
    );
    fixtureValue.git('add', receiptPath);
    fixtureValue.git('commit', '--quiet', '-m', message);
    return fixtureValue.git('rev-parse', 'HEAD');
  }

  function reuseResult(fixtureValue, currentHead) {
    return findReusableVerification({
      baseRef: 'verification-base',
      stages: ['full'],
      updates: [{ localRef: 'refs/heads/feature', localObjectId: currentHead }],
      root: fixtureValue.root,
    });
  }

  it('reuses the verified parent only for a schema-valid, correlated receipt-only child', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository);

    expect(reuseResult(repository, currentHead)).toEqual({
      reusable: true,
      headCommit: currentHead,
      verifiedHeadCommit: repository.verifiedHead,
    });
  });

  it('rejects a forged JSON object in the added receipt path', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, { contents: {} });

    expect(reuseResult(repository, currentHead).reusable).toBe(false);
  });

  it('rejects closure trailers that do not exactly match the added path', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, {
      message: 'chore: close work run\n\nWork-Run: run-1\nWork-Receipt: g0-r1',
    });

    expect(reuseResult(repository, currentHead).reusable).toBe(false);
  });

  it('rejects duplicate work-run trailers', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, {
      message: 'chore: close work run\n\nWork-Run: run-1\nWork-Run: run-1\nWork-Receipt: g0-r0',
    });

    expect(reuseResult(repository, currentHead).reusable).toBe(false);
  });

  it('rejects work-run lines outside the final trailer block', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, {
      message: 'chore: close work run\n\nWork-Run: run-1\nWork-Receipt: g0-r0\n\nnot a trailer',
    });

    expect(reuseResult(repository, currentHead).reusable).toBe(false);
  });

  it('accepts work-run trailers inside a terminal block with another Git trailer', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, {
      message:
        'chore: close work run\n\nWork-Run: run-1\nWork-Receipt: g0-r0\nSigned-off-by: Harness <harness@example.test>',
    });

    expect(reuseResult(repository, currentHead)).toEqual({
      reusable: true,
      headCommit: currentHead,
      verifiedHeadCommit: repository.verifiedHead,
    });
  });

  it('rejects a schema-valid receipt whose coordinates do not match its path', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, {
      contents: includedReceipt(repository.verifiedHead, 'other-run'),
    });

    expect(reuseResult(repository, currentHead).reusable).toBe(false);
  });

  it('rejects a valid receipt whose identity does not name the verified parent', () => {
    const repository = fixture();
    const currentHead = commitClosure(repository, {
      contents: includedReceipt('0'.repeat(40)),
    });

    expect(reuseResult(repository, currentHead).reusable).toBe(false);
  });
});

describe('realDirtyLines over a real repository (INFRA-101)', () => {
  // A real `git status` run, not a string fixture — the bug this guards against was in how the output
  // is READ (a trimming helper ate the leading status column), which a string fixture cannot reach.
  const roots = [];
  const repo = () => {
    const root = makeTemp('receipt-churn-');
    roots.push(root);
    const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8' });
    git('init', '-q');
    git('config', 'user.email', 'test@example.com');
    git('config', 'user.name', 'test');
    git('config', 'commit.gpgsign', 'false');
    mkdirSync(path.join(root, '.agents/evals/lessons'), { recursive: true });
    for (const f of ['auto-lessons.md', 'weekly-digest.md']) {
      writeFileSync(path.join(root, '.agents/evals/lessons', f), 'committed\n');
    }
    writeFileSync(path.join(root, 'source.txt'), 'committed\n');
    git('add', '-A');
    git('commit', '-qm', 'base');
    return { root, git };
  };
  afterAll(() => {
    for (const root of roots) rmSync(root, { recursive: true, force: true });
  });

  it('reports nothing on a genuinely clean tree', () => {
    const { root } = repo();
    expect(realDirtyLines(root)).toEqual([]);
    expect(isCleanTree(root)).toBe(true);
  });

  it('treats a tree dirty with ONLY the churn files as clean — the receipt can be written', () => {
    const { root } = repo();
    for (const f of ['auto-lessons.md', 'weekly-digest.md']) {
      writeFileSync(path.join(root, '.agents/evals/lessons', f), 'regenerated\n');
    }
    // Precondition: git really does see both as dirty, so the assertion below is not vacuous.
    const raw = execFileSync('git', ['status', '--porcelain'], { cwd: root, encoding: 'utf8' });
    expect(raw.split('\n').filter(Boolean)).toHaveLength(2);

    expect(realDirtyLines(root)).toEqual([]);
    expect(isCleanTree(root)).toBe(true);
  });

  it('still refuses when anything else is dirty, and names it', () => {
    const { root } = repo();
    writeFileSync(path.join(root, '.agents/evals/lessons/auto-lessons.md'), 'regenerated\n');
    writeFileSync(path.join(root, 'source.txt'), 'edited\n');

    const dirty = realDirtyLines(root);
    expect(dirty).toHaveLength(1);
    expect(dirty[0]).toContain('source.txt');
    expect(isCleanTree(root)).toBe(false);
  });

  it('counts a staged churn file as churn, and an untracked non-churn file as dirt', () => {
    const { root, git } = repo();
    writeFileSync(path.join(root, '.agents/evals/lessons/weekly-digest.md'), 'regenerated\n');
    git('add', '.agents/evals/lessons/weekly-digest.md');
    expect(realDirtyLines(root)).toEqual([]);

    writeFileSync(path.join(root, 'brand-new.txt'), 'untracked\n');
    expect(realDirtyLines(root).some((l) => l.includes('brand-new.txt'))).toBe(true);
  });
});

describe('bounded git status', () => {
  it('sets a finite timeout and output limit', () => {
    const run = vi.fn(() => ({ status: 0, stdout: ' M source.txt\n', stderr: '' }));
    expect(boundedGitStatus('/repo', { run, timeoutMs: 1234 })).toBe(' M source.txt\n');
    expect(run).toHaveBeenCalledWith(
      'git',
      ['status', '--porcelain=v1', '--untracked-files=all'],
      expect.objectContaining({ cwd: '/repo', timeout: 1234, maxBuffer: 8 * 1024 * 1024 }),
    );
  });

  it('reports command timeout and non-zero exit distinctly', () => {
    expect(() =>
      boundedGitStatus('/repo', {
        run: () => ({ error: Object.assign(new Error('late'), { code: 'ETIMEDOUT' }) }),
      }),
    ).toThrow(/git status timed out/i);
    expect(() =>
      boundedGitStatus('/repo', {
        run: () => ({ status: 1, stdout: '', stderr: 'index unavailable' }),
      }),
    ).toThrow(/git status failed: index unavailable/i);
  });
});
