import { execFileSync } from 'node:child_process';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import { makeTemp } from './make-temp.mjs';

import {
  AUTO_GENERATED_CHURN,
  createVerificationReceipt,
  isAutoGeneratedChurn,
  isCleanTree,
  pushedObjectsMatchVerifiedHead,
  realDirtyLines,
  receiptMatches,
  shouldWriteFullReceipt,
} from '../verification-receipt.mjs';

const identity = {
  headCommit: 'head-a',
  headTree: 'tree-a',
  baseCommit: 'base-a',
  profile: 'verify-like-ci/full',
  stages: ['format-check', 'harness-self-test'],
  nodeVersion: 'v22.14.0',
  pnpmVersion: '8.15.4',
  lockfileHash: 'lock-a',
  ownerFingerprint: 'owners-a',
};

describe('exact verification receipts', () => {
  it('matches only an identical successful full-gate identity', () => {
    const receipt = createVerificationReceipt(identity);
    expect(receiptMatches(receipt, identity)).toBe(true);

    for (const [field, value] of [
      ['headCommit', 'head-b'],
      ['headTree', 'tree-b'],
      ['baseCommit', 'base-b'],
      ['profile', 'pre-push/fast'],
      ['nodeVersion', 'v24.0.0'],
      ['pnpmVersion', '9.0.0'],
      ['lockfileHash', 'lock-b'],
      ['ownerFingerprint', 'owners-b'],
    ]) {
      expect(receiptMatches(receipt, { ...identity, [field]: value }), field).toBe(false);
    }
    expect(receiptMatches(receipt, { ...identity, stages: ['format-check'] })).toBe(false);
  });

  it('treats missing, malformed, partial, failed, and unknown-version receipts as misses', () => {
    expect(receiptMatches(null, identity)).toBe(false);
    expect(receiptMatches({}, identity)).toBe(false);
    expect(
      receiptMatches({ ...createVerificationReceipt(identity), status: 'fail' }, identity),
    ).toBe(false);
    expect(
      receiptMatches({ ...createVerificationReceipt(identity), schemaVersion: 999 }, identity),
    ).toBe(false);
  });

  it('writes evidence only for a complete clean successful stage set', () => {
    const complete = {
      exitCode: 0,
      clean: true,
      selectedStages: ['a', 'b'],
      requiredStages: ['a', 'b'],
    };
    expect(shouldWriteFullReceipt(complete)).toBe(true);
    expect(shouldWriteFullReceipt({ ...complete, clean: false })).toBe(false);
    expect(shouldWriteFullReceipt({ ...complete, exitCode: 1 })).toBe(false);
    expect(shouldWriteFullReceipt({ ...complete, selectedStages: ['a'] })).toBe(false);
  });

  it('reuses evidence only when every non-delete pushed object is the verified HEAD', () => {
    const update = (localObjectId, localRef = 'refs/heads/feature') => ({
      localRef,
      localObjectId,
    });
    expect(pushedObjectsMatchVerifiedHead([update('head-a')], 'head-a')).toBe(true);
    expect(pushedObjectsMatchVerifiedHead([update('head-b')], 'head-a')).toBe(false);
    expect(
      pushedObjectsMatchVerifiedHead(
        [update('head-a'), update('0'.repeat(40), '(delete)')],
        'head-a',
      ),
    ).toBe(true);
  });
});

describe('auto-generated churn is the only dirt that does not count (INFRA-101)', () => {
  // `git status --porcelain` puts the staged column in position 0, so an unstaged edit begins with a
  // SPACE. Every fixture here keeps it — dropping it is the bug this suite exists to catch.
  const unstaged = (p) => ` M ${p}`;
  const staged = (p) => `M  ${p}`;

  it('recognises each churn file, in the exact form git emits', () => {
    expect([...AUTO_GENERATED_CHURN]).toEqual([
      '.agents/evals/lessons/auto-lessons.md',
      '.agents/evals/lessons/weekly-digest.md',
    ]);
    for (const file of AUTO_GENERATED_CHURN) {
      expect(isAutoGeneratedChurn(unstaged(file))).toBe(true);
      expect(isAutoGeneratedChurn(staged(file))).toBe(true);
    }
  });

  it('does not except anything else, including its own directory', () => {
    expect(isAutoGeneratedChurn(unstaged('packages/agent-cli/src/cli.ts'))).toBe(false);
    expect(isAutoGeneratedChurn(unstaged('.agents/evals/lessons/hand-written.md'))).toBe(false);
    expect(isAutoGeneratedChurn(unstaged('.agents/evals/README.md'))).toBe(false);
  });

  it('is not fooled by a path that merely ends with a churn filename', () => {
    expect(isAutoGeneratedChurn(unstaged('vendor/.agents/evals/lessons/auto-lessons.md'))).toBe(
      false,
    );
  });

  it('needs the leading status column — a trimmed line must NOT match', () => {
    // The defect this asserts against: reading porcelain output through a helper that trims makes the
    // FIRST line lose its leading space, so `slice(3)` reads one character into the path and the
    // churn stops being recognised. That is what starved the receipt for five consecutive runs.
    expect(isAutoGeneratedChurn('.agents/evals/lessons/auto-lessons.md')).toBe(false);
    expect(isAutoGeneratedChurn('M .agents/evals/lessons/auto-lessons.md')).toBe(false);
  });
});

describe('realDirtyLines over a real repository (INFRA-101)', () => {
  // A real `git status` run, not a string fixture — the bug this guards against was in how the output
  // is READ (a trimming helper ate the leading status column), which a string fixture cannot reach.
  const roots = [];
  const repo = () => {
    const root = makeTemp('receipt-churn-');
    roots.push(root);
    const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8' });
    git('init', '-q');
    git('config', 'user.email', 'test@example.com');
    git('config', 'user.name', 'test');
    git('config', 'commit.gpgsign', 'false');
    mkdirSync(path.join(root, '.agents/evals/lessons'), { recursive: true });
    for (const f of ['auto-lessons.md', 'weekly-digest.md']) {
      writeFileSync(path.join(root, '.agents/evals/lessons', f), 'committed\n');
    }
    writeFileSync(path.join(root, 'source.txt'), 'committed\n');
    git('add', '-A');
    git('commit', '-qm', 'base');
    return { root, git };
  };
  afterAll(() => {
    for (const root of roots) rmSync(root, { recursive: true, force: true });
  });

  it('reports nothing on a genuinely clean tree', () => {
    const { root } = repo();
    expect(realDirtyLines(root)).toEqual([]);
    expect(isCleanTree(root)).toBe(true);
  });

  it('treats a tree dirty with ONLY the churn files as clean — the receipt can be written', () => {
    const { root } = repo();
    for (const f of ['auto-lessons.md', 'weekly-digest.md']) {
      writeFileSync(path.join(root, '.agents/evals/lessons', f), 'regenerated\n');
    }
    // Precondition: git really does see both as dirty, so the assertion below is not vacuous.
    const raw = execFileSync('git', ['status', '--porcelain'], { cwd: root, encoding: 'utf8' });
    expect(raw.split('\n').filter(Boolean)).toHaveLength(2);

    expect(realDirtyLines(root)).toEqual([]);
    expect(isCleanTree(root)).toBe(true);
  });

  it('still refuses when anything else is dirty, and names it', () => {
    const { root } = repo();
    writeFileSync(path.join(root, '.agents/evals/lessons/auto-lessons.md'), 'regenerated\n');
    writeFileSync(path.join(root, 'source.txt'), 'edited\n');

    const dirty = realDirtyLines(root);
    expect(dirty).toHaveLength(1);
    expect(dirty[0]).toContain('source.txt');
    expect(isCleanTree(root)).toBe(false);
  });

  it('counts a staged churn file as churn, and an untracked non-churn file as dirt', () => {
    const { root, git } = repo();
    writeFileSync(path.join(root, '.agents/evals/lessons/weekly-digest.md'), 'regenerated\n');
    git('add', '.agents/evals/lessons/weekly-digest.md');
    expect(realDirtyLines(root)).toEqual([]);

    writeFileSync(path.join(root, 'brand-new.txt'), 'untracked\n');
    expect(realDirtyLines(root).some((l) => l.includes('brand-new.txt'))).toBe(true);
  });
});
