// harness-coverage: verification-receipt-storage.mjs
// harness-coverage: bounded-git-status.mjs
import { spawnSync } from 'node:child_process';
import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('node:child_process', () => ({ spawnSync: vi.fn() }));

import * as cleanTree from '../verification-receipt.mjs';
import {
  AUTO_GENERATED_CHURN,
  isAutoGeneratedChurn,
  isCleanTree,
  realDirtyLines,
} from '../verification-receipt.mjs';
import { boundedGitStatus } from '../bounded-git-status.mjs';

beforeEach(() => {
  vi.mocked(spawnSync).mockReset().mockReturnValue({ status: 0, stdout: '', stderr: '' });
});

it('retains shared clean-tree helpers but exposes no full-CI receipt API', () => {
  expect(Object.keys(cleanTree).sort()).toEqual([
    'AUTO_GENERATED_CHURN',
    'isAutoGeneratedChurn',
    'isCleanTree',
    'realDirtyLines',
  ]);
});

describe('auto-generated churn is the only dirt that does not count (INFRA-101)', () => {
  // `git status --porcelain` puts the staged column in position 0, so an unstaged edit begins with a
  // SPACE. Every fixture here keeps it — dropping it is the bug this suite exists to catch.
  const unstaged = (p) => ` M ${p}`;
  const staged = (p) => `M  ${p}`;

  it('recognises each churn file, in the exact form git emits', () => {
    expect([...AUTO_GENERATED_CHURN]).toEqual([
      '.agents/evals/lessons/auto-lessons.md',
      '.agents/evals/lessons/weekly-digest.md',
    ]);
    for (const file of AUTO_GENERATED_CHURN) {
      expect(isAutoGeneratedChurn(unstaged(file))).toBe(true);
      expect(isAutoGeneratedChurn(staged(file))).toBe(true);
    }
  });

  it('does not except anything else, including its own directory', () => {
    expect(isAutoGeneratedChurn(unstaged('packages/agent-cli/src/cli.ts'))).toBe(false);
    expect(isAutoGeneratedChurn(unstaged('.agents/evals/lessons/hand-written.md'))).toBe(false);
    expect(isAutoGeneratedChurn(unstaged('.agents/evals/README.md'))).toBe(false);
  });

  it('is not fooled by a path that merely ends with a churn filename', () => {
    expect(isAutoGeneratedChurn(unstaged('vendor/.agents/evals/lessons/auto-lessons.md'))).toBe(
      false,
    );
  });

  it('needs the leading status column — a trimmed line must NOT match', () => {
    // The defect this asserts against: reading porcelain output through a helper that trims makes the
    // FIRST line lose its leading space, so `slice(3)` reads one character into the path and the
    // churn stops being recognised. That is what starved the receipt for five consecutive runs.
    expect(isAutoGeneratedChurn('.agents/evals/lessons/auto-lessons.md')).toBe(false);
    expect(isAutoGeneratedChurn('M .agents/evals/lessons/auto-lessons.md')).toBe(false);
  });
});

describe('realDirtyLines through bounded status without a Git fixture', () => {
  it.each([
    ['', [], true],
    [
      ' M .agents/evals/lessons/auto-lessons.md\n M .agents/evals/lessons/weekly-digest.md\n',
      [],
      true,
    ],
    ['M  .agents/evals/lessons/weekly-digest.md\n?? new.txt\n', ['?? new.txt'], false],
    [' M .agents/evals/lessons/auto-lessons.md\n M source.txt\n', [' M source.txt'], false],
  ])('preserves porcelain columns and filters only owned churn: %j', (stdout, expected, clean) => {
    vi.mocked(spawnSync).mockReturnValue({ status: 0, stdout, stderr: '' });
    expect(realDirtyLines('/subject')).toEqual(expected);
    expect(isCleanTree('/subject')).toBe(clean);
    expect(spawnSync).toHaveBeenCalledTimes(2);
    for (const call of vi.mocked(spawnSync).mock.calls) {
      expect(call).toEqual([
        'git',
        ['status', '--porcelain=v1', '--untracked-files=all'],
        expect.objectContaining({ cwd: '/subject' }),
      ]);
    }
  });

  it('propagates failed status instead of certifying a clean tree', () => {
    vi.mocked(spawnSync).mockReturnValue({ status: 1, stderr: 'index unavailable' });
    expect(() => realDirtyLines('/subject')).toThrow('index unavailable');
    expect(() => isCleanTree('/subject')).toThrow('index unavailable');
  });
});

describe('bounded git status', () => {
  it('sets a finite timeout and output limit', () => {
    const run = vi.fn(() => ({ status: 0, stdout: ' M source.txt\n', stderr: '' }));
    expect(boundedGitStatus('/repo', { run, timeoutMs: 1234 })).toBe(' M source.txt\n');
    expect(run).toHaveBeenCalledWith(
      'git',
      ['status', '--porcelain=v1', '--untracked-files=all'],
      expect.objectContaining({ cwd: '/repo', timeout: 1234, maxBuffer: 8 * 1024 * 1024 }),
    );
  });

  it('reports command timeout and non-zero exit distinctly', () => {
    expect(() =>
      boundedGitStatus('/repo', {
        run: () => ({ error: Object.assign(new Error('late'), { code: 'ETIMEDOUT' }) }),
      }),
    ).toThrow(/git status timed out/i);
    expect(() =>
      boundedGitStatus('/repo', {
        run: () => ({ status: 1, stdout: '', stderr: 'index unavailable' }),
      }),
    ).toThrow(/git status failed: index unavailable/i);
  });
});
