import {
  committedAssistant,
  contextState,
  historyStructure,
  json,
  literal,
  messages,
  nonNegativeInteger,
  optional,
  ownerPath,
  record,
  required,
  schemas,
  strings,
} from './field-decoders.js';
import { decodeBackgroundJobGroupEvent } from '../session-record-codec/background-group-decoders.js';
import { decodeBackgroundTaskEvent } from '../session-record-codec/background-task-event-decoders.js';
import { decodeMemoryEvent } from '../session-record-codec/event-decoders.js';
import { decodeMessage } from '../session-record-codec/message-decoders.js';
import { decodeBoolean, decodeNumber, decodeString } from '../session-record-codec/scalars.js';

import type { TSessionLogEventName } from '../session-log-events.js';
import type { TPayloadShape } from './field-decoders.js';

// The required members are drawn from production emitters; optional members include values
// omitted by the logger when a producer supplies undefined.
export const PAYLOADS = {
  session_init: {
    cwd: required(decodeString),
    systemPromptLength: required(nonNegativeInteger),
    systemPrompt: required(decodeString),
    toolSchemas: required(schemas),
    model: required(decodeString),
    provider: required(decodeString),
  },
  session_shutdown: { reason: required(decodeString) },
  session_shutdown_step_error: { step: required(decodeString), error: required(decodeString) },
  context: {
    maxTokens: required(decodeNumber),
    usedTokens: required(decodeNumber),
    usedPercentage: required(decodeNumber),
    remainingPercentage: required(decodeNumber),
  },
  context_compact: {
    trigger: required(decodeString),
    before: required(contextState),
    after: required(contextState),
  },
  error: {
    message: required(decodeString),
    stack: required(decodeString),
    historyLength: required(nonNegativeInteger),
  },
  history_mutation: {
    executionId: optional(decodeString),
    conversationId: optional(decodeString),
    round: optional(nonNegativeInteger),
    batchId: optional(decodeString),
    usageObservationId: optional(decodeString),
    providerId: optional(decodeString),
    modelId: optional(decodeString),
    providerError: optional(decodeBoolean),
    contextOverflow: optional(decodeBoolean),
    mutation: required(literal('append_message')),
    index: required(nonNegativeInteger),
    message: required(decodeMessage),
  },
  provider_request: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    provider: required(decodeString),
    model: required(decodeString),
    effort: optional(decodeString),
    messages: required(messages),
    tools: optional(schemas),
  },
  provider_native_raw_payload: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    provider: required(decodeString),
    apiSurface: optional(decodeString),
    payloadKind: required(literal('request', 'response', 'stream_event')),
    sequence: required(nonNegativeInteger),
    payload: optional(json),
    metadata: optional(record),
  },
  provider_stream_raw_delta: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    sequence: required(nonNegativeInteger),
    delta: required(decodeString),
  },
  provider_response_raw: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    effort: optional(decodeString),
    response: required(decodeMessage),
    responseKind: required(decodeString),
  },
  provider_response_normalized: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    response: required(decodeMessage),
    toolCallsCount: optional(nonNegativeInteger),
  },
  structured_output_transport: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    provider: required(decodeString),
    model: required(decodeString),
    mechanism: required(literal('response_schema', 'json_object', 'none')),
    provenance: required(literal('catalog', 'vendor-default', 'undeclared', 'unverified-endpoint')),
    sent: required(decodeBoolean),
    schemaInPrompt: required(decodeBoolean),
    reason: optional(decodeString),
  },
  assistant_message_committed: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    message: required(committedAssistant),
  },
  tool_execution_request: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    batchId: optional(decodeString),
    index: optional(nonNegativeInteger),
    toolName: required(decodeString),
    toolCallId: required(decodeString),
    parameters: required(record),
    ownerPath: optional(ownerPath),
  },
  tool_execution_result: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    batchId: optional(decodeString),
    index: optional(nonNegativeInteger),
    toolName: optional(decodeString),
    toolCallId: optional(decodeString),
    success: required(decodeBoolean),
    result: optional(json),
    error: optional(decodeString),
    metadata: optional(record),
  },
  tool_batch_started: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    batchId: optional(decodeString),
    mode: required(literal('parallel', 'sequential')),
    maxConcurrency: required(nonNegativeInteger),
    requestCount: required(nonNegativeInteger),
    tools: required(strings),
  },
  tool_message_committed: {
    executionId: required(decodeString),
    conversationId: optional(decodeString),
    round: required(nonNegativeInteger),
    batchId: optional(decodeString),
    index: optional(nonNegativeInteger),
    message: required(decodeMessage),
  },
  background_task_event: {
    backgroundEventType: optional(decodeString),
    backgroundEvent: optional(decodeBackgroundTaskEvent),
    data: optional(decodeBackgroundTaskEvent),
    taskId: optional(decodeString),
    originToolCallId: optional(decodeString),
  },
  background_job_group_event: {
    backgroundJobGroupEvent: optional(decodeBackgroundJobGroupEvent),
    data: optional(decodeBackgroundJobGroupEvent),
  },
  memory_event: { memoryEvent: optional(decodeMemoryEvent), data: optional(decodeMemoryEvent) },
  user: { content: required(decodeString) },
  pre_run: {
    historyLength: required(nonNegativeInteger),
    historyChars: required(nonNegativeInteger),
    historyEstTokens: required(nonNegativeInteger),
    input: required(decodeString),
    history: required(messages),
    model: required(decodeString),
    provider: required(decodeString),
    maxTokens: required(decodeNumber),
    nativeWebSearchSupported: required(decodeBoolean),
    nativeWebSearchEnabled: required(decodeBoolean),
    nativeWebFetchSupported: required(decodeBoolean),
    nativeWebFetchEnabled: required(decodeBoolean),
  },
  text_delta: { delta: required(decodeString) },
  assistant: {
    content: required(decodeString),
    historyLength: required(nonNegativeInteger),
    estimatedChars: required(nonNegativeInteger),
    history: required(messages),
    historyStructure: required(historyStructure),
  },
  tool_call: { tool: required(decodeString), args: required(record) },
  tool_result: {
    tool: required(decodeString),
    success: required(decodeBoolean),
    dataChars: required(nonNegativeInteger),
    truncated: required(decodeBoolean),
  },
  tool_blocked: { tool: required(decodeString), reason: required(decodeString) },
  tool_denied: { tool: required(decodeString), reason: required(decodeString) },
  server_tool: { tool: required(decodeString) },
} satisfies Record<TSessionLogEventName, TPayloadShape>;
