name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'packages/*/src/**'
      - 'apps/docs/**'
      - 'scripts/docs-generator.js'
      - 'scripts/prepare-docs.js'
      - 'typedoc.json'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

# 수동으로 워크플로우를 실행할 수 있게 함

# 저장소에 쓰기 권한 허용
permissions:
  contents: write
  pages: write
  id-token: write

# 동시에 하나의 배포만 허용
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Build Documentation
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./apps/docs/.vitepress/dist
          branch: gh-pages
          clean: true